### ISSUE TITLE
Add lexicon for Japanese

### ISSUE THREAD

**Issue by kevincobain2000** [knuppe/vader#1]
Resources

Tokenizer - https://github.com/ikawaha/kagome
Lexicon - `<googling it>`, perhaps if you know of a lexicon that is available

**Comment by knuppe** [comment]
I have no knowledge of Japanese, so adapting the lexicon requires a good understanding of the language. Sagan lexicons are different then the original VADER implementation.

Another point is that most of the lexicons available on the internet for languages other than English are translations that lack careful analysis.
