### ISSUE TITLE
Should just go:embed `lexicons/en/en.zip`

### ISSUE THREAD

**Issue by kevincobain2000** [knuppe/vader#3]
It'd be better to just embed the lexicons using `go:embed` so the user of the lib can avoid this extra step.

```
func main(){
	// you need to download de lexicon zip files.
	vader, err := NewVader("lexicons/en/en.zip")
```

**Comment by knuppe** [comment]
The problem is the size of the lexicons, and not everyone uses the default Sagan lexicon, for example, I have personal lexicons that I can't publish because I don't have licensing permission.

**Comment by kevincobain2000** [comment]
Makes sense
